In [1]:
from ctypes import *
dll = WinDLL("CTA-railway.dll")

In [2]:
dll.initSim()

376

In [3]:
dll.runSim()

1709469856

In [4]:
dll.SimIsFinished()

1

In [11]:
dll.getTotalTravelTime.restype = c_double   
totalTravelTime = dll.getTotalTravelTime()/3600.0
print('%.1f' % totalTravelTime)

1646451.6


In [12]:
dll.getTotalDelay.restype = c_double   
totalDelay = dll.getTotalDelay()/3600.0
print('%.1f' % totalDelay)

1546790.8


In [16]:
# 分析各个站的delay
import numpy as np

dll.getStationDelay.argtypes = [c_int, c_int]
dll.getStationDelay.restype = c_double
delays = []
for station in range(252):
    buffer = [station]
    buffer.append(dll.getStationDelay(station, 0))
    buffer.append(dll.getStationDelay(station, 1))
    buffer.append(buffer[0]+buffer[1])
    delays.append(buffer)

delay = np.array(delays)
print(delay[np.lexsort(-delay.T)])

[[ 5.20000000e+01  2.19118860e+08  0.00000000e+00  2.19118912e+08]
 [ 7.80000000e+01  1.92020640e+08 -1.55869200e+07  1.92020718e+08]
 [ 6.10000000e+01  1.27100760e+08 -6.58857000e+06  1.27100821e+08]
 ...
 [ 2.00000000e+01 -5.37119100e+07 -3.15028800e+07 -5.37118900e+07]
 [ 9.20000000e+01 -9.24807000e+07 -1.45435290e+08 -9.24806080e+07]
 [ 3.50000000e+01 -1.32060900e+08 -1.56060000e+05 -1.32060865e+08]]
